#!/bin/bash

if [ -z "$FORKED" ]; then
    export FORKED=true
    $0 "$@" &
    exit 0
fi
config_file=/etc/through-vpn.conf

# wait for tunnel
while ! ping -c 1 -w 5 -q $5 &> /dev/null ; do
    sleep 0.5
done

test -e $config_file || exit 0

for host in `cat $config_file` ; do
    through-vpn $host
done
