#!/bin/bash

if ! xdotool search --classname urxvt-scratchpad ; then
    urxvt -name urxvt-scratchpad -e ensure-tmux $DISPLAY &>/dev/null &
    while ! xdotool search --classname urxvt-scratchpad ; do
        sleep 0.05
    done
    # hack for preserving scratchpad geometry.
    # currently geometry partially lost when window is moved into scratchpad
    i3-msg '[instance="urxvt-scratchpad"] move to scratchpad'
    i3-msg '[instance="urxvt-scratchpad"] scratchpad show'
    sleep 0.1

    # detect multihead
    width_percent=100
    if [ "`xrandr | awk '$2 == "connected"' | wc -l`" -gt 1 ] ; then
        width_percent=50
    fi

    xdotool search --classname urxvt-scratchpad windowsize ${width_percent}% 74%
    xdotool search --classname urxvt-scratchpad windowmove 0 0
    i3-msg '[instance="urxvt-scratchpad"] scratchpad show'
fi

i3-msg '[instance="urxvt-scratchpad"] scratchpad show'

