#!/bin/bash

if ! xdotool search --classname urxvt-scratchpad ; then
    urxvt -name urxvt-scratchpad -e ensure-tmux $DISPLAY &>/dev/null &
    sleep 0.1
    # hack for preserving scratchpad geometry.
    # currently geometry partially lost when window is moved into scratchpad
    i3-msg '[instance="urxvt-scratchpad"] move to scratchpad'
    i3-msg '[instance="urxvt-scratchpad"] scratchpad show'
    sleep 0.1
    xdotool search --classname urxvt-scratchpad windowsize 100% 74%
    xdotool search --classname urxvt-scratchpad windowmove 0 0
    i3-msg '[instance="urxvt-scratchpad"] scratchpad show'
fi

i3-msg '[instance="urxvt-scratchpad"] scratchpad show'

